name: Deployment Pipeline
on:
  push:
    branches:
      - main
  # pull_request:
  #   branches: [main]
  #   types: [opened, synchronize]
jobs:
  server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install Firebase CLI
        run: npm i -g firebase-tools
      - name: Install the dependencies
        run: cd server && npm ci
      - name: Build
        run: cd server && npm run build
      # - name: Test
      #   run: cd server && npm run test
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
          GOOGLE_CREDENTIALS_TEST: ${{ secrets.GOOGLE_CREDENTIALS_TEST }}
      - name: Deploy
        # if: ${{ github.event.name == 'push' && !contains(join(github.event.commits.*.message, ', '), '#skip') }}
        # run: cd server && npm run deploy:ci
        run: firebase deploy --only functions
        env:
          # GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_SANDRO_20240214  }}
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN  }}
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

  client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - name: Install the dependencies
        run: cd client && npm ci
      - name: Build
        run: cd client && npm run build
      - name: Deploy
        # if: ${{ github.event.name == 'push' && !contains(join(github.event.commits.*.message, ', '), '#skip') }}
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_SANDRO_20240214 }}"
          channelId: live
          projectId: sandro-20240214
