name: Deployment Pipeline
on:
  push:
    branches:
      - main
  # pull_request:
  #   branches: [main]
  #   types: [opened, synchronize]
jobs:
  server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install Firebase CLI
        run: npm i -g firebase-tools
      - name: Set the working directory
        run: cd server
      - name: Install the dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test
      - name: Deploy
        if: ${{ github.event.name == 'push' && !contains(join(github.event.commits.*.message, ', '), '#skip') }}
        run: firebase deploy --only functions
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_SANDRO_20240214  }}

  client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - name: Install the dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Deploy
        if: ${{ github.event.name == 'push' && !contains(join(github.event.commits.*.message, ', '), '#skip') }}
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_SANDRO_20240214 }}"
          channelId: live
          projectId: sandro-20240214
